name: Bug Report
description: Report something that's broken
labels: ['bug']
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you do, what did you expect, and what happened instead?
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: textarea
    id: media
    attributes:
      label: Screenshots / recordings
      description: Optional, but helps a lot.
    validations:
      required: false
