export const IpcChannels = {
  GetCaptureSources: 'capture:get-sources',
  StartRecording: 'recording:start',
  StopRecording: 'recording:stop',
  PauseRecording: 'recording:pause',
  ResumeRecording: 'recording:resume',
  RecordingStateChanged: 'recording:state-changed',
  SaveRecordingFile: 'recording:save-file',
  StartCursorTracking: 'cursor:start-tracking',
  StopCursorTracking: 'cursor:stop-tracking',
  CursorPositionSample: 'cursor:position-sample',
  CursorClickSample: 'cursor:click-sample',
  OpenProject: 'project:open',
  SaveProject: 'project:save',
  ExportVideo: 'export:start',
  ExportProgress: 'export:progress',
  ShowSaveExportDialog: 'dialog:show-save-export',
  SaveScreenshot: 'screenshot:save',
  CopyScreenshot: 'screenshot:copy',
  CaptureScreenshot: 'screenshot:capture',
  SelectCaptureRegion: 'screenshot:select-region',
  RegionSelectComplete: 'region-select:complete',
  RegionSelectCancel: 'region-select:cancel',
  RegionSelectGetContentOrigin: 'region-select:get-content-origin',
  GetSettings: 'settings:get',
  SetSettings: 'settings:set',
  RegisterShortcut: 'shortcuts:register',
  UnregisterShortcut: 'shortcuts:unregister',
  WindowMinimize: 'window:minimize',
  WindowHide: 'window:hide',
  WindowRestore: 'window:restore',
  WindowToggleMaximize: 'window:toggle-maximize',
  WindowClose: 'window:close',
  WindowIsMaximized: 'window:is-maximized',
  WindowMaximizeChanged: 'window:maximize-changed',
  GetScreenRecordingStatus: 'permissions:get-screen-recording-status',
  OpenScreenRecordingSettings: 'permissions:open-screen-recording-settings',
  ShowNotification: 'notification:show',
  PickOsCaptureSource: 'screenshot:pick-os-source'
} as const;

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels];
